# Generated by Django 4.0.4 on 2022-06-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_filter_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filter_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.filter_price'),
        ),
    ]
