# Generated by Django 4.0.4 on 2022-06-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_discount_cartitems_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='discount',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
