# Generated by Django 4.0.4 on 2022-06-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='images',
        ),
    ]
