# Generated by Django 4.0.4 on 2022-06-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_filter_price_price_filter_price_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='filter_price',
        ),
        migrations.DeleteModel(
            name='Filter_Price',
        ),
    ]
