# Generated by Django 4.0.4 on 2022-06-23 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
